#!/usr/bin/env python3
"""
Builds weekly-tests.js from the readable sources in content/weeks_*.py.

Each source file adds to a dict W:
    W[n] = dict(title="...", essays=["...", "...", "..."],
                q=[("question", "correct", "wrong1", "wrong2", "wrong3"), ...])

The script refuses to build if a question is malformed or repeated (within the weekly
banks or against the 90-question quiz in index.php), then writes the bank base64-encoded
(same obfuscation as the main quiz pool) to weekly-tests.js.

Usage:  python3 build_weekly.py
"""
import base64
import glob
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
MIN_QUESTIONS = 20
ESSAYS_PER_WEEK = 3


def norm(text):
    return re.sub(r"[^a-z0-9 ]", "", text.lower().replace("'", "").replace("-", " ")).strip()


def load_sources():
    W = {}
    for path in sorted(glob.glob(os.path.join(ROOT, "content", "weeks_*.py"))):
        ns = {"W": W}
        with open(path, encoding="utf-8") as fh:
            exec(compile(fh.read(), path, "exec"), ns)
    return W


def load_main_pool():
    src = open(os.path.join(ROOT, "index.php"), encoding="utf-8").read()
    m = re.search(r'fullQuizPool = JSON\.parse\(atob\("([^"]+)"\)\)', src)
    return json.loads(base64.b64decode(m.group(1)).decode("utf-8"))


def main():
    W = load_sources()
    problems = []
    seen = {}
    for q in load_main_pool():
        seen[norm(q["question"])] = "main quiz"

    out = {}
    for n in range(1, 16):
        if n not in W:
            problems.append("week %d is missing" % n)
            continue
        week = W[n]
        if len(week["essays"]) < ESSAYS_PER_WEEK:
            problems.append("week %d has fewer than %d essay topics" % (n, ESSAYS_PER_WEEK))
        if len(week["q"]) < MIN_QUESTIONS:
            problems.append("week %d has %d questions (need %d)" % (n, len(week["q"]), MIN_QUESTIONS))
        questions = []
        for i, row in enumerate(week["q"], 1):
            where = "week %d q%d" % (n, i)
            if len(row) != 5:
                problems.append(where + ": needs question + correct + 3 wrong answers")
                continue
            text, correct, wrong = row[0].strip(), row[1].strip(), [w.strip() for w in row[2:]]
            options = [correct] + wrong
            if len({o.lower() for o in options}) != 4 or any(not o for o in options):
                problems.append(where + ": answers must be 4 different non-empty options")
            key = norm(text)
            if key in seen:
                problems.append("%s repeats a question from %s: %s" % (where, seen[key], text[:60]))
            seen[key] = where
            questions.append({"question": text, "correctAnswer": correct, "wrongAnswers": wrong})
        out[str(n)] = {"title": week["title"], "essays": week["essays"], "questions": questions}

    if problems:
        print("BUILD FAILED:")
        for p in problems:
            print(" -", p)
        return 1

    blob = base64.b64encode(json.dumps(out, ensure_ascii=True, separators=(",", ":")).encode("ascii")).decode("ascii")
    with open(os.path.join(ROOT, "weekly-tests.js"), "w", encoding="utf-8") as fh:
        fh.write("/* Weekly test banks (HK6002 syllabus, weeks 1-15). Generated by build_weekly.py - do not edit. */\n")
        fh.write('const WEEKLY_TESTS = JSON.parse(atob("%s"));\n' % blob)
    total = sum(len(w["questions"]) for w in out.values())
    print("OK: %d weeks, %d questions, %d essay topics -> weekly-tests.js (%d KB)" % (
        len(out), total, sum(len(w["essays"]) for w in out.values()), len(blob) // 1024))
    return 0


if __name__ == "__main__":
    sys.exit(main())
