# Weeks 4-6 (HK6002 syllabus). Format: (question, correct, wrong1, wrong2, wrong3)

W[4] = dict(
    title="The Great Steppe in the Golden Horde Period",
    essays=[
        "Explain the role of Ak Orda (the White Horde) in the formation of Kazakh statehood.",
        "Explain how the Mongol conquest of Central Asia under Genghis Khan changed the political map of the steppe.",
        "Explain the significance of the Golden Horde's administrative system, including the yarlyk and the yam, for governing its vast territories.",
        "Explain how the breakup of the Chagatai Ulus and the rise of Moghulistan paved the way for the later Kazakh Khanate.",
    ],
    q=[
        ("In which year was Temujin proclaimed Genghis Khan at a great kurultai?", "1206", "1219", "1240", "1256"),
        ("Which event triggered Genghis Khan's campaign against Khorezm in 1219?", "The execution of Mongol merchants and envoys at Otrar", "A Kipchak raid on the Mongol capital", "A dispute over Silk Road taxes with China", "The death of his son Juchi"),
        ("Which ruler of Khorezm faced Genghis Khan's invasion of Central Asia in 1219-1221?", "Muhammad II, the Khorezmshah", "Satuk Bughra Khan", "Timur", "Tokhtamysh"),
        ("In 1223 Mongol forces defeated Rus princes and the Cumans (Kipchaks) at which river?", "The Kalka", "The Terek", "The Ili", "The Ural (Zhaiyk)"),
        ("Which khan founded the Golden Horde after the western campaign and made Sarai his capital?", "Batu Khan", "Berke Khan", "Uzbek Khan", "Tokhtamysh"),
        ("Which Golden Horde khan made Islam the state religion in the early 14th century?", "Uzbek Khan", "Batu Khan", "Juchi", "Tokhtamysh"),
        ("What was the Mongol charter that confirmed a Rus prince's right to rule called?", "The yarlyk", "The firman", "The berat", "The tamga"),
        ("What was the Mongol network of relay stations for messengers and officials called?", "The yam", "The kurultai", "The zhuz", "The ulus"),
        ("The Ak Orda was ruled by descendants of which son of Juchi?", "Orda-Ichen", "Batu", "Shiban", "Berke"),
        ("Which city on the Syr Darya was the capital of the Ak Orda?", "Sygnak", "Sarai-Batu", "Bukhara", "Kashgar"),
        ("Kerey and Janibek were descendants of which Ak Orda khan?", "Urus Khan", "Batu Khan", "Tokhtamysh", "Edigei"),
        ("Which son of Genghis Khan received the Central Asian lands that formed the Chagatai Ulus?", "Chagatai", "Ogedei", "Tolui", "Juchi"),
        ("Moghulistan emerged around 1347-1348 from the breakup of which state?", "The Chagatai Ulus", "The Ak Orda", "The Nogai Horde", "The Kimak Khaganate"),
        ("Who wrote the Tarikh-i Rashidi, an important source on Moghulistan and the early Kazakh Khanate?", "Mirza Muhammad Haidar Dulati", "Kadyrgali Zhalayiri", "Abu al-Ghazi", "Rashid al-Din"),
        ("Which Mangyt emir is regarded as the founder of the Nogai Horde tradition?", "Edigei", "Kerey", "Abulkhair", "Kasym"),
        ("The Nogai Horde's core lands lay between which two rivers?", "The Volga and the Yaik (Ural)", "The Ili and the Chu", "The Irtysh and the Ob", "The Amu Darya and the Syr Darya"),
        ("In which year was Abulkhair proclaimed khan of the Nomadic Uzbeks?", "1428", "1219", "1465", "1723"),
        ("Which grandson of Abulkhair captured Samarkand in 1500 and founded a dynasty in Transoxiana?", "Muhammad Shaybani", "Kasym Khan", "Kenesary", "Babur"),
        ("Which conqueror crushed Tokhtamysh of the Golden Horde in 1391 and 1395?", "Timur", "Edigei", "Kenesary", "Abulkhair"),
        ("In which year did Genghis Khan die?", "1227", "1206", "1260", "1219"),
    ],
)

W[5] = dict(
    title="The Kazakh Khanate from the 15th to the 18th Century",
    essays=[
        "Explain the importance of Kasym Khan's law code, the Qasqa Zholy, for the Kazakh Khanate.",
        "Explain the social structure of the Kazakh Khanate, including the roles of the toré, the bi and the three zhuzes.",
        "Explain the causes and consequences of the Dzungar invasions, including the Aktaban Shubyryndy, for the Kazakh people.",
        "Explain the significance of Zhety Zhargy and the work of Tole Bi, Kazybek Bi and Aiteke Bi for Kazakh customary law.",
    ],
    q=[
        ("In which year is the Kazakh Khanate traditionally said to have been founded?", "1465", "1428", "1723", "1822"),
        ("Where did Kerey and Janibek settle after leaving the state of Abulkhair?", "The Chu valley in Zhetysu (Moghulistan)", "The Ural steppe", "The Siberian forest zone", "The Caspian shore"),
        ("Under Kasym Khan the population of the khanate is often estimated at about how many people?", "About one million", "About 100,000", "About ten million", "About fifty million"),
        ("What is Kasym Khan's law code called?", "Qasqa Zholy", "Zhety Zhargy", "Eski Zholy", "The Constitution"),
        ("Which khan's legal code is known as 'Eski Zholy' (The Old Road)?", "Yesim Khan", "Kasym Khan", "Tauke Khan", "Haqnazar Khan"),
        ("Which three biys are associated with the creation of Zhety Zhargy?", "Tole Bi, Kazybek Bi and Aiteke Bi", "Abai, Shokan and Ybyrai", "Kerey, Janibek and Kasym", "Isatay, Makhambet and Syrym"),
        ("Tauke Khan ruled the Kazakhs during roughly which years?", "About 1680-1718", "About 1465-1480", "About 1823-1845", "About 1511-1518"),
        ("Zhangir Khan won the Battle of Orbulak in 1643 against which enemy?", "The Dzungars", "The Siberian Khanate", "Bukhara", "The Nogai Horde"),
        ("In which year did the Dzungar invasion known as Aktaban Shubyryndy begin?", "1723", "1643", "1730", "1822"),
        ("Which battle of 1730 is remembered as a major Kazakh victory over the Dzungars?", "The Battle of Anyrakay", "The Battle of Talas", "The Battle of Kalka", "The Battle of Otrar"),
        ("Which zhuz occupied the western part of the Kazakh lands?", "The Junior (Kishi) Zhuz", "The Senior (Uly) Zhuz", "The Middle (Orta) Zhuz", "The Inner Horde"),
        ("What does the term 'toré' (the 'white bone') describe in Kazakh society?", "Sultans descended from Genghis Khan", "Ordinary herders", "Judges and legal experts", "Court poets"),
        ("What role did the 'bi' play in Kazakh society?", "A judge and arbiter of customary law", "A military commander", "A tax collector", "A court poet"),
        ("Which Siberian khan was defeated in the 1580s campaign led by Yermak?", "Kuchum", "Tauke", "Ablai", "Kenesary"),
        ("The Dzungar Khanate was destroyed by which empire in the 1750s?", "Qing China", "The Russian Empire", "The Ottoman Empire", "Persia"),
        ("Which of these is a Kazakh heroic epic?", "Koblandy Batyr", "The Shahnameh", "The Kalevala", "The Iliad"),
        ("Which city with the Yasawi mausoleum served as a political and spiritual centre of the khanate?", "Turkistan", "Almaty", "Kokshetau", "Pavlodar"),
        ("Which late 16th-century Kazakh khan worked to restore unity and regional influence?", "Haqnazar Khan", "Kasym Khan", "Tauke Khan", "Ablai Khan"),
        ("Why did the Dzungar invasions so badly weaken the Kazakhs?", "They devastated pastures and forced mass flight and famine", "They introduced a single elected parliament", "They ended nomadism voluntarily", "They caused a boom in Silk Road trade"),
        ("Kasym Khan's reign (about 1511-1518) is remembered mainly for what?", "Uniting the Kazakhs and expanding the khanate's territory", "Ending nomadic life", "Accepting Russian protection", "Founding the Alash Party"),
    ],
)

W[6] = dict(
    title="Kazakhstan in the 18th to Early 20th Centuries",
    essays=[
        "Explain why the power of the khans was abolished in the 1820s and what changed after the 1822 and 1824 charters.",
        "Explain the causes and course of Kenesary Kasymuly's uprising and its place in Kazakh resistance to colonial rule.",
        "Explain how the Steppe Regulations of 1891 and Stolypin's resettlement policy changed land use and Kazakh society.",
        "Explain how Chokan Valikhanov and Ibray Altynsarin contributed to Kazakh scholarship and education in the 19th century.",
    ],
    q=[
        ("In which year did Khan Abulkhair of the Junior Zhuz accept Russian protection?", "1731", "1723", "1822", "1868"),
        ("Which Russian empress accepted the Junior Zhuz's request for protection in 1731?", "Anna Ioannovna", "Catherine II", "Elizabeth", "Peter I"),
        ("In which year was Ablai proclaimed khan by representatives of the three zhuzes in Turkistan?", "1771", "1740", "1822", "1841"),
        ("By which decade had the Senior Zhuz been incorporated into the Russian Empire?", "The 1860s", "The 1730s", "The 1780s", "The 1900s"),
        ("Which Russian statesman drafted the 1822 Charter on the Siberian Kirghiz?", "Mikhail Speransky", "Pyotr Stolypin", "Sergei Witte", "Prince Potemkin"),
        ("The 1822 Charter ended the rule of khans first in which zhuz?", "The Middle Zhuz", "The Junior Zhuz", "The Senior Zhuz", "None of them"),
        ("Under the 1867-1868 reforms the Kazakh lands were divided into what?", "Oblasts governed by Russian military governors", "Independent khanates", "Three autonomous zhuzes", "Ethnic republics"),
        ("What was a key effect of the 1891 Steppe Regulations on land?", "Nomad lands were declared state property and opened to settlement", "Land was returned to the khans", "Nomads received private title to all pastures", "All land taxes were abolished"),
        ("Which prime minister's reforms after 1906 encouraged mass peasant resettlement onto the Kazakh steppe?", "Pyotr Stolypin", "Sergei Witte", "Alexander Kerensky", "Vladimir Lenin"),
        ("In which year was the Orenburg-Tashkent railway completed?", "1906", "1856", "1931", "1954"),
        ("Syrym Datuly led an uprising in which zhuz?", "The Junior Zhuz", "The Middle Zhuz", "The Senior Zhuz", "None of them"),
        ("Which poet-warrior took part in the 1836-1838 uprising and voiced its ideals in verse?", "Makhambet Utemisuly", "Abai", "Zhambyl", "Shakarim"),
        ("Kenesary Kasymuly was the grandson of which khan?", "Ablai Khan", "Tauke Khan", "Abulkhair", "Kasym Khan"),
        ("In which year was Kenesary proclaimed khan?", "1841", "1731", "1822", "1868"),
        ("How did Kenesary's struggle end in 1847?", "He was killed in fighting with Kyrgyz forces", "He was executed in Omsk", "He signed a treaty with Russia", "He died in exile in Siberia"),
        ("Which fortress founded in 1716 on the Irtysh became a key Russian base in the steppe?", "Omsk", "Verny", "Kostanay", "Aktobe"),
        ("Zhankozha Nurmukhamedov led resistance mainly along which river?", "The Syr Darya", "The Irtysh", "The Ural", "The Ili"),
        ("Which Kazakh scholar-explorer travelled to Kashgar in 1858-1859?", "Chokan Valikhanov", "Abai", "Ibray Altynsarin", "Akhmet Baitursynov"),
        ("Ibray Altynsarin is remembered mainly for what?", "Founding schools and writing Kazakh-language textbooks", "Leading the 1916 uprising", "Founding the Alash Party", "Writing Zhety Zhargy"),
        ("The 1868-1869 uprisings were mainly a reaction to what?", "The 1867-1868 reforms with new taxes and land policies", "The abolition of serfdom", "The Russian Revolution of 1905", "The Great Patriotic War"),
    ],
)
