# Weeks 7-9 (HK6002 syllabus). Format: (question, correct, wrong1, wrong2, wrong3)

W[7] = dict(
    title="Kazakhstan at the Beginning of the 20th Century",
    essays=[
        "Analyze the causes, course and consequences of the 1916 Central Asian uprising in Kazakhstan.",
        "Explain the role of the Alash movement and the Alash-Orda government in the national movement of the Kazakhs.",
        "Discuss how Jadidism, new-method schools and the press (Aiqap, Qazaq) contributed to the rise of the Kazakh intelligentsia.",
    ],
    q=[
        ("Which Crimean Tatar educator is regarded as the father of Jadidism?", "Ismail Gasprinski", "Mustafa Shokay", "Ibray Altynsarin", "Chokan Valikhanov"),
        ("Which teaching method gave Jadidism its name (usul-i jadid)?", "The new phonetic method of teaching", "The old memorization method", "The military drill method", "Teaching in Latin only"),
        ("Who founded the journal Aiqap in 1911?", "Mirzhaqyp Dulatuly", "Alikhan Bokeikhanov", "Akhmet Baitursynov", "Mukhtar Auezov"),
        ("Who edited the newspaper Qazaq, which appeared from 1913?", "Akhmet Baitursynov", "Abai Kunanbayev", "Ibray Altynsarin", "Chokan Valikhanov"),
        ("Which 1909 poetry collection by Mirzhaqyp Dulatuly called on the Kazakhs to awaken?", "Oyan, Qazaq!", "Masa", "The Book of Words", "Kutadgu Bilig"),
        ("What did the 1905 Karkaraly Petition demand?", "Civil rights, protection of land and representation for the Kazakhs", "Independence from Russia", "The return of the khan's power", "The abolition of the State Duma"),
        ("What was Ittifaq al-Muslimin?", "A political union of Russia's Muslims formed in 1905", "A Kazakh military alliance of the 15th century", "A Russian trade guild", "A Soviet youth movement"),
        ("Which Kazakh leader signed the Vyborg Appeal after the dissolution of the First State Duma in 1906?", "Alikhan Bokeikhanov", "Amangeldy Imanov", "Kenesary Kasymuly", "Ablai Khan"),
        ("Why did the June 1916 decree provoke revolt in Kazakhstan?", "Kazakhs, previously exempt from military service, were called up for rear labour", "It banned nomadism", "It closed all schools", "It abolished the zhuzes"),
        ("Which age group of men was called up for rear work under the June 1916 decree?", "Men aged 19 to 43", "Boys aged 12 to 16", "Men aged 50 to 65", "Women only"),
        ("Who led the rebels of the Turgai region in 1916 together with Abdighapar Zhanbosynuly?", "Amangeldy Imanov", "Kenesary Kasymuly", "Alikhan Bokeikhanov", "Ablai Khan"),
        ("What happened to many Kazakhs and Kyrgyz of Semirechye after the repression of 1916?", "Hundreds of thousands fled across the border to China", "They were resettled in Siberia by choice", "They joined the Red Army in a body", "They founded a new khanate"),
        ("What did 'dual power' mean in Kazakhstan after the February Revolution of 1917?", "The Soviets ruled alongside the Provisional Government's committees", "Two khans ruled the steppe", "Russia and China ruled jointly", "The army and the church ruled together"),
        ("In which city was the First All-Kazakh Congress held in July 1917?", "Orenburg", "Semey", "Almaty", "Omsk"),
        ("Which autonomy was proclaimed by the Second All-Kazakh Congress in December 1917?", "The Alash Autonomy", "The Turkestan Autonomy", "The Bukhara Emirate", "The Kazakh SSR"),
        ("Which city was the seat of the Alash-Orda government?", "Semey (Semipalatinsk)", "Orenburg", "Tashkent", "Omsk"),
        ("Who chaired the Alash-Orda government?", "Alikhan Bokeikhanov", "Akhmet Baitursynov", "Mirzhaqyp Dulatuly", "Mustafa Shokay"),
        ("Which Alash leader is known as the 'Teacher of the Nation'?", "Akhmet Baitursynov", "Alikhan Bokeikhanov", "Mukhtar Auezov", "Turar Ryskulov"),
        ("Which prominent Kazakh political figure took part in the leadership of the Turkestan (Kokand) Autonomy?", "Mustafa Shokay", "Amangeldy Imanov", "Abai Kunanbayev", "Kenesary Kasymuly"),
        ("How did the Turkestan (Kokand) Autonomy end?", "Bolshevik forces crushed it in February 1918", "It joined Alash-Orda peacefully", "It ruled until 1930", "It was dissolved by a referendum"),
    ],
)

W[8] = dict(
    title="Midterm Review of Weeks 1 to 7",
    essays=[
        "Describe the main stages of Kazakhstan's history from the Stone Age to the Kazakh Khanate.",
        "What were the main stages of Kazakhstan's incorporation into the Russian Empire, and how did the Kazakh people resist?",
        "What was the role of the 1916 uprising and the Alash movement in the national liberation struggle of the Kazakhs?",
    ],
    q=[
        ("Which sequence lists these periods correctly, earliest first?", "Stone Age, Bronze Age, Early Iron Age, Turkic era", "Bronze Age, Stone Age, Early Iron Age, Turkic era", "Early Iron Age, Stone Age, Bronze Age, Turkic era", "Turkic era, Stone Age, Bronze Age, Early Iron Age"),
        ("Which sequence lists these states correctly, earliest first?", "Turkic Khaganate, Golden Horde, Kazakh Khanate, Alash-Orda", "Golden Horde, Turkic Khaganate, Kazakh Khanate, Alash-Orda", "Kazakh Khanate, Turkic Khaganate, Alash-Orda, Golden Horde", "Alash-Orda, Kazakh Khanate, Golden Horde, Turkic Khaganate"),
        ("Which of these events happened first?", "The formation of the Kazakh Khanate (1465)", "Aktaban Shubyryndy (1723)", "The Junior Zhuz's request for Russian protection (1731)", "Kenesary's uprising (1837)"),
        ("Which of these events happened last?", "The Second All-Kazakh Congress (December 1917)", "The 1916 uprising", "The abolition of khan rule in the 1820s", "Kenesary's uprising"),
        ("Which order of these events is correct, earliest first?", "Battle of Talas, siege of Otrar, Battle of Orbulak, 1916 uprising", "Siege of Otrar, Battle of Talas, 1916 uprising, Battle of Orbulak", "Battle of Orbulak, Battle of Talas, siege of Otrar, 1916 uprising", "1916 uprising, Battle of Orbulak, Battle of Talas, siege of Otrar"),
        ("Which pairing of people and region of Kazakhstan is correct?", "Kangly - the Syr Darya basin; Sarmatians - the west", "Kangly - the Altai; Sarmatians - the southeast", "Kangly - the Caspian coast; Sarmatians - the Irtysh", "Kangly - Zhetysu; Sarmatians - the Syr Darya delta"),
        ("Which pairing of ruler and achievement is correct?", "Kasym Khan - Qasqa Zholy; Tauke Khan - Zhety Zhargy", "Kasym Khan - Zhety Zhargy; Tauke Khan - Qasqa Zholy", "Yesim Khan - Qasqa Zholy; Kasym Khan - Eski Zholy", "Tauke Khan - Eski Zholy; Yesim Khan - Zhety Zhargy"),
        ("Which pairing of scholar and work is correct?", "Yusuf Balasaguni - Kutadgu Bilig; Mahmud al-Kashgari - Diwan Lughat at-Turk", "Yusuf Balasaguni - Diwan Lughat at-Turk; Mahmud al-Kashgari - Kutadgu Bilig", "Al-Farabi - Kutadgu Bilig; Yusuf Balasaguni - Tarikh-i Rashidi", "Mahmud al-Kashgari - Tarikh-i Rashidi; Al-Farabi - Diwan Lughat at-Turk"),
        ("Which pairing of leader and uprising is correct?", "Kenesary Kasymuly - 1837-1847; Syrym Datuly - 1783-1797", "Kenesary Kasymuly - 1783-1797; Syrym Datuly - 1837-1847", "Isatay Taimanov - 1916; Amangeldy Imanov - 1836-1838", "Syrym Datuly - 1916; Isatay Taimanov - 1837-1847"),
        ("Which pairing of rulers and states is correct?", "Kerey and Janibek - the Kazakh Khanate; Abulkhair - the State of the Nomadic Uzbeks", "Kerey and Janibek - Moghulistan; Abulkhair - the Kazakh Khanate", "Edigei - the Kazakh Khanate; Kerey - the Nogai Horde", "Abulkhair - the Nogai Horde; Janibek - the Chagatai Ulus"),
        ("Which change tied the Kazakh lands most closely to the Russian economy in the late 19th and early 20th centuries?", "Railways and peasant settlement", "The revival of the Dzungar trade", "The Mongol postal system", "The Silk Road caravans"),
        ("Why is the 1916 uprising seen as a turning point for the Kazakh national movement?", "It exposed colonial injustice and pushed the intelligentsia toward political autonomy", "It ended Russian rule immediately", "It restored the khanate", "It created the Golden Horde"),
        ("What common aim led both Jadids and Alash leaders to promote schools and newspapers?", "Modernizing society and preserving national identity through education", "Preparing troops for war", "Restoring Dzungar rule", "Spreading Buddhism"),
        ("Why did the breakup of the Golden Horde matter for the Kazakhs?", "Successor states such as Ak Orda and Moghulistan set the stage for the Kazakh Khanate", "It ended nomadic life in the steppe", "It brought Russian rule directly", "It created the zhuz system overnight"),
        ("What do kurgans, petroglyphs and runic inscriptions have in common as historical sources?", "They are material or written evidence left by steppe peoples", "They are all Russian archival documents", "They are all 20th-century memoirs", "They are all Persian court chronicles"),
        ("Which weeks does the syllabus midterm assignment cover?", "Weeks 1 to 7", "Weeks 1 to 4", "Weeks 5 to 15", "Weeks 1 to 15"),
        ("In what form does the syllabus ask students to answer the midterm questions?", "As essays of 1-2 pages per question", "As multiple-choice tests only", "As oral songs", "As group posters only"),
        ("Which social and political order included the roles of khan, sultan, bi and batyr?", "The traditional order of the Kazakh Khanate", "The Turkic Khaganate only", "The government of Soviet Kazakhstan", "The Alash-Orda cabinet"),
        ("Which pair of Russian measures fits 'ended khan rule' and 'changed the legal status of nomad land', in that order?", "The 1822-1824 charters; the 1891 Steppe Regulations", "The 1891 Steppe Regulations; the 1822-1824 charters", "The 1867 Regulations; the 1731 protectorate", "The 1916 decree; the 1917 congresses"),
        ("What did the Turkic Khaganate and the Golden Horde have in common as steppe empires?", "Both united many nomadic peoples under one dynasty and controlled Eurasian trade routes", "Both were founded by Russian tsars", "Both were Christian states", "Both were founded in the 20th century"),
    ],
)

W[9] = dict(
    title="Civil War and Kazakhstan in the 1920s",
    essays=[
        "Describe the Civil War in Kazakhstan (1918-1920): the establishment of Soviet power, the Red and White forces, partisan movements and local resistance.",
        "Explain the formation of Kazakh statehood within the USSR, from the Kyrgyz ASSR (1920) to the national-territorial delimitation of 1924-1925.",
        "Assess the New Economic Policy in Kazakhstan, its achievements and contradictions, and the cultural developments of the 1920s.",
    ],
    q=[
        ("Which White admiral headed the anti-Bolshevik government based in Omsk?", "Alexander Kolchak", "Anton Denikin", "Pyotr Wrangel", "Lavr Kornilov"),
        ("Which Red commander led the Turkestan Front in 1919-1920?", "Mikhail Frunze", "Leon Trotsky", "Semyon Budyonny", "Alexander Kolchak"),
        ("Which leader of the 1916 uprising supported the Reds and died in 1919?", "Amangeldy Imanov", "Alikhan Bokeikhanov", "Akhmet Baitursynov", "Mustafa Shokay"),
        ("Which forces were the main opponents of the Red Army in Kazakhstan during the Civil War?", "White forces and Cossack armies such as Dutov's", "Dzungar forces", "British troops only", "Qing armies"),
        ("Who was Alexander Dutov?", "An Orenburg Cossack ataman who fought the Bolsheviks", "A Kazakh khan", "A Bolshevik commander", "A Soviet writer"),
        ("Which city was the first capital of the Kyrgyz (Kazakh) ASSR created in 1920?", "Orenburg", "Almaty", "Semey", "Tashkent"),
        ("In which year was the Kyrgyz ASSR renamed the Kazakh ASSR?", "1925", "1920", "1929", "1936"),
        ("In which year did Alma-Ata (Almaty) become the capital of Soviet Kazakhstan?", "1929", "1920", "1925", "1991"),
        ("In which year did Kazakhstan become a full union republic, the Kazakh SSR?", "1936", "1920", "1925", "1940"),
        ("What was the aim of the national-territorial delimitation of 1924-1925?", "To redraw Central Asian borders along national lines", "To restore the khanates", "To unite all republics into one", "To create a caliphate"),
        ("What was the 'prodrazvyorstka' under Military Communism?", "Compulsory requisition of grain and livestock", "A voluntary trade fair", "A tax on imports", "A school reform"),
        ("What worsened the famine of 1921-1922 in Kazakhstan?", "Requisitions, drought and the disruption of the Civil War", "A Dzungar invasion", "A Mongol conquest", "A world war"),
        ("What replaced requisitions when the New Economic Policy began in 1921?", "A tax in kind", "Collective farms", "Forced labour armies", "A ban on all trade"),
        ("Which party leader in Kazakhstan launched the 'Little October' campaign?", "Filipp Goloshchekin", "Turar Ryskulov", "Mikhail Frunze", "Nikita Khrushchev"),
        ("Which social group was targeted as class enemy in the 'Little October' campaign?", "Wealthy stock-owners (bais) and clan elites", "Factory workers", "Red Army officers", "Teachers"),
        ("Which script replaced the Arabic-based Kazakh alphabet in 1929?", "The Latin alphabet", "The Cyrillic alphabet", "The Greek alphabet", "Old Turkic runes"),
        ("Which writer wrote the play Enlik-Kebek, dated to 1917?", "Mukhtar Auezov", "Sabit Mukanov", "Ilyas Zhansugurov", "Beimbet Mailin"),
        ("What did many Alash-Orda leaders do after the Civil War turned in favour of the Reds?", "They ceased resistance and cooperated with the Soviet government under an amnesty", "They moved the government to Beijing", "They founded a new khanate", "They joined the White armies"),
        ("What was 'likbez' in the 1920s?", "A campaign to eliminate illiteracy", "A military draft", "A grain tax", "A religious festival"),
        ("Which Soviet policy of the 1920s promoted local languages and native cadres in government?", "Korenizatsiya (indigenization)", "Collectivization", "Dekulakization", "Russification"),
    ],
)
