# Weeks 13-15 (HK6002 syllabus). Format: (question, correct, wrong1, wrong2, wrong3)

W[13] = dict(
    title="The Formation of Independent Kazakhstan",
    essays=[
        "Explain the causes of the collapse of the USSR in 1991 and the declaration of independence of Kazakhstan on December 16, 1991.",
        "Analyze Kazakhstan's socio-economic modernization: the transition to a market economy in the 1990s, privatization, the agricultural crisis and economic stabilization in the 2000s.",
        "Discuss nation-building in independent Kazakhstan: the Assembly of People of Kazakhstan, interreligious dialogue, the Bolashak program and the preservation of national heritage (Madeni Mura).",
    ],
    q=[
        ("Which document of December 21, 1991 enlarged the CIS to include Kazakhstan?", "The Alma-Ata Declaration", "The Belovezha Accords", "The Helsinki Act", "The Treaty of Nerchinsk"),
        ("On which date did Kazakhstan declare its independence?", "December 16, 1991", "October 25, 1990", "August 30, 1995", "March 17, 1991"),
        ("On which date is Constitution Day celebrated, marking the 1995 referendum?", "August 30", "December 16", "July 6", "March 22"),
        ("In which year was Kazakhstan's national currency, the tenge, introduced?", "1993", "1991", "1995", "1998"),
        ("In which year was the capital officially moved from Almaty to Akmola (later Astana)?", "1997", "1991", "2005", "1929"),
        ("What was a main effect of price liberalization in Kazakhstan in 1992?", "Very high inflation", "Deflation", "A budget surplus", "Rapid growth of wages"),
        ("Which measures marked Kazakhstan's transition to a market economy in the 1990s?", "Privatization and price liberalization", "Collectivization and requisitions", "Nationalization and rationing", "Five-year plans and sovkhozes"),
        ("What was a feature of the agricultural crisis of the 1990s?", "Collapse of state farms, falling output and rural depopulation", "A record grain export boom", "A new Virgin Lands campaign", "Mass collectivization"),
        ("Which script is Kazakhstan gradually adopting for the Kazakh language under reforms launched in 2017?", "The Latin script", "The Arabic script", "The Greek script", "The Old Turkic script"),
        ("In which year was the Bolashak international scholarship program established?", "1993", "1991", "2004", "1998"),
        ("In which year was the Digital Kazakhstan program launched?", "2017", "1993", "2004", "2022"),
        ("In which year was the Cultural Heritage (Madeni Mura) program launched?", "2004", "1991", "2017", "2022"),
        ("In which year was the Assembly of People of Kazakhstan created?", "1995", "1991", "2004", "2010"),
        ("What is the aim of the Assembly of People of Kazakhstan?", "Promoting interethnic harmony and cooperation", "Organizing military service", "Setting oil prices", "Electing the president directly"),
        ("In which year was the first Congress of Leaders of World and Traditional Religions held in Astana?", "2003", "1991", "1995", "2022"),
        ("What aim does the Congress of Leaders of World and Traditional Religions pursue?", "Promoting interreligious dialogue and peace", "Choosing new borders", "Deciding oil quotas", "Selecting the capital"),
        ("Which pyramid-shaped building in Astana hosts the Congress of Leaders of World and Traditional Religions?", "The Palace of Peace and Accord", "Bayterek", "Khan Shatyr", "Nur Alem"),
        ("Which strategy announced in 2012 set the goal of joining the 30 most developed countries by 2050?", "The Kazakhstan-2050 Strategy", "The Kazakhstan-2030 Strategy", "Rukhani Zhangyru", "Digital Kazakhstan"),
        ("Which oil pipeline system opened in 2001 carries Kazakh oil to the Black Sea?", "The Caspian Pipeline Consortium", "Druzhba", "Baku-Tbilisi-Ceyhan", "Nord Stream"),
        ("What did Kazakhstan do with the nuclear weapons it inherited from the USSR?", "It gave them up and joined the NPT as a non-nuclear state", "It kept and expanded them", "It sold them to China", "It buried them at Baikonur"),
    ],
)

W[14] = dict(
    title="Kazakhstan in New Geo-Economic and Geo-Political Conditions",
    essays=[
        "What is the essence of the multi-vector foreign policy of Kazakhstan? Provide examples.",
        "Analyze the Eurasian idea and Kazakhstan's role in integration, from the CIS to the Eurasian Economic Union.",
        "Assess Kazakhstan's bilateral relations with European countries, Islamic countries and the major powers (the USA, China and Russia).",
    ],
    q=[
        ("What does 'multi-vector' foreign policy mean?", "Balanced, pragmatic relations with several major powers at once", "An alliance with a single superpower", "Isolation from all neighbours", "Membership only in military blocs"),
        ("In which city and year did Nazarbayev propose the idea of a Eurasian Union?", "Moscow, 1994", "Beijing, 1991", "Astana, 2010", "Washington, 2002"),
        ("In which year did the Eurasian Economic Union begin operating?", "2015", "1991", "2000", "2008"),
        ("What is the CIS?", "A post-Soviet regional organization formed in 1991", "A NATO branch", "A Central Asian oil cartel", "An agency of the European Union"),
        ("Which military alliance includes Kazakhstan and Russia among its members?", "The CSTO", "NATO", "SEATO", "The Warsaw Pact"),
        ("Which organization founded in 2001 counts Kazakhstan, China and Russia among its founding members?", "The Shanghai Cooperation Organisation", "NATO", "ASEAN", "OPEC"),
        ("Which forum did Nazarbayev propose in 1992 to build trust and security in Asia?", "CICA", "The G20", "BRICS", "The Non-Aligned Movement"),
        ("In 2010 Kazakhstan became the first former Soviet republic to chair which organization?", "The OSCE", "NATO", "The European Union", "The WTO"),
        ("What role did Kazakhstan hold in the UN Security Council in 2017-2018?", "A non-permanent member", "A permanent member with veto power", "Chair of the General Assembly", "An observer only"),
        ("In which year did Kazakhstan join the World Trade Organization?", "2015", "1995", "2001", "2020"),
        ("Which international exhibition on 'Future Energy' did Astana host in 2017?", "Expo 2017", "The Winter Olympics", "The World Cup", "The Asian Games"),
        ("In which city did Xi Jinping announce the Silk Road Economic Belt in 2013?", "Astana", "Almaty", "Moscow", "Beijing"),
        ("Which Kazakhstan facility is leased to Russia?", "The Baikonur Cosmodrome", "The Kapchagay reservoir", "The Semipalatinsk test site", "The Tengiz oil field"),
        ("Which organization of Muslim states did Kazakhstan join in 1995?", "The Organization of Islamic Cooperation", "OPEC", "NATO", "The G7"),
        ("With which union did Kazakhstan sign an enhanced partnership agreement in 2015?", "The European Union", "ASEAN", "The African Union", "Mercosur"),
        ("What did the 2006 treaty signed in Semey create?", "A Central Asian nuclear-weapon-free zone", "A Eurasian customs union", "A joint Caspian fleet", "A common army"),
        ("In which city was the 2018 convention on the legal status of the Caspian Sea signed?", "Aktau", "Atyrau", "Baku", "Astrakhan"),
        ("With which country does Kazakhstan share its longest land border?", "Russia", "China", "Uzbekistan", "Turkmenistan"),
        ("What did Nazarbayev's Eurasian idea aim at?", "Economic integration based on equality and voluntary participation", "A single military command under Moscow", "The merger of all states into one country", "A ban on foreign trade"),
        ("What is Khorgos on the border with China?", "A major border trade and logistics centre", "A nuclear test site", "A Silk Road ruin", "A Caspian oil field"),
    ],
)

W[15] = dict(
    title="New Kazakhstan Renewal and Modernization",
    essays=[
        "Describe the goals and directions of the 'Rukhani Zhangyru' (Spiritual Renewal) program.",
        "Explain the idea of 'New Kazakhstan' (Zhana Qazaqstan) and the current socio-political reforms.",
        "Analyze democratization, decentralization, anti-corruption and justice reforms in 2022-2025 under the strategy 'Fair State, Prosperous Society, Strong Nation'.",
    ],
    q=[
        ("In which year did Kassym-Jomart Tokayev become President of Kazakhstan?", "2019", "1991", "2011", "2022"),
        ("Which events in early January 2022 preceded the push for 'New Kazakhstan' reforms?", "Mass protests and violent unrest", "A nuclear accident", "A world war", "A Mongol invasion"),
        ("On which date was the constitutional referendum of 2022 held?", "June 5, 2022", "January 5, 2022", "September 1, 2019", "November 20, 2022"),
        ("Which slogan sums up the vision of President Tokayev's reforms?", "Fair State, Prosperous Society, Strong Nation", "Kazakhstan 2030", "Strong President, Weak Parliament", "One Belt, One Road"),
        ("Under the 2022 reforms, how long is the President's single term?", "Seven years, without re-election", "Five years, with two terms", "Ten years", "Unlimited"),
        ("Which electoral system was used for the 2023 elections to the Mazhilis?", "A mixed system of party lists and single-member districts", "Party lists only", "Appointed deputies only", "Rule by a khan"),
        ("The reforms lowered the number of members needed to register a political party to about how many?", "20,000", "200,000", "2,000", "2 million"),
        ("Which principle did Tokayev announce in 2019?", "A state that listens to its citizens", "A state that commands its citizens", "Rule by one party only", "No state at all"),
        ("Which court, absent since 1995, was restored in 2023?", "The Constitutional Court", "The Supreme Court", "The Court of Arbitration", "An international court"),
        ("What did the decentralization of local governance aim to do?", "Give local levels more authority and accountability", "Move all power to the capital", "Abolish local government", "End all elections"),
        ("What does the national idea 'Mangilik El' express?", "The aim of an eternal, enduring nation", "A temporary union of states", "A military doctrine", "An oil strategy"),
        ("In which year was Rukhani Zhangyru (Spiritual Modernization) launched?", "2017", "1991", "2004", "2022"),
        ("What does 'Zhana Kazakhstan' mean in English?", "New Kazakhstan", "Great Kazakhstan", "Ancient Kazakhstan", "Free Kazakhstan"),
        ("What was the subject of the 2024 referendum in Kazakhstan?", "Building a nuclear power plant", "Joining the EU", "Moving the capital", "Restoring the Senate"),
        ("What does strengthening parliament mean in the reform agenda?", "Giving parliament a stronger role in lawmaking and oversight", "Abolishing parliament", "Limiting the president to a veto", "Returning power to khans"),
        ("What is the aim of anti-corruption measures in the reforms?", "To strengthen public integrity and trust in institutions", "To raise taxes", "To end elections", "To close schools"),
        ("Which idea underlies the 'Fair State' element of the strategy?", "Equality before the law and accountable institutions", "Rule by decree", "Rule by one family", "Rule by the military"),
        ("Which goal does the 'Prosperous Society' element emphasise?", "Higher living standards, opportunity and social welfare", "Isolation from trade", "Abandoning cities", "Ending education"),
        ("What does the 'Strong Nation' element stress?", "Civic unity, patriotism and national identity", "Military rule", "Ethnic exclusion", "Economic autarky"),
        ("Which period does the syllabus give for the 'New Kazakhstan' reforms?", "2022-2025", "1991-2000", "1965-1985", "1928-1932"),
    ],
)
