# Weeks 1-3 (HK6002 syllabus). Format: (question, correct, wrong1, wrong2, wrong3)

W[1] = dict(
    title="Introduction and Prehistoric Kazakhstan",
    essays=[
        "Describe the main stages of the Stone Age and the Bronze Age in Kazakhstan and the archaeological evidence for each stage.",
        "Explain why the Botai culture is considered important for the history of horse domestication and for the origins of nomadic civilization.",
        "Discuss how the Andronovo and Begazy-Dandybai cultures shaped the Bronze Age of the steppe and prepared the ground for nomadic civilization.",
    ],
    q=[
        ("Which alloy gave the Bronze Age its name?", "Copper mixed with tin", "Iron mixed with carbon", "Gold mixed with silver", "Lead mixed with zinc"),
        ("Which metal was the first to be widely worked by people during the Eneolithic?", "Copper", "Iron", "Aluminium", "Steel"),
        ("Which Kazakh petroglyph site near Almaty was added to the UNESCO World Heritage List in 2004?", "Tamgaly", "Issyk", "Berel", "Saraishyk"),
        ("Microliths, small finely worked stone blades, are the signature tools of which Stone Age period?", "The Mesolithic", "The Bronze Age", "The Eneolithic", "The Early Iron Age"),
        ("Which change in the natural environment at the end of the last Ice Age shaped the Mesolithic world?", "Warming as the glaciers retreated", "A sudden drop in sea level everywhere", "The disappearance of all forests", "The formation of the Caspian Sea"),
        ("Which craft, used for cooking and food storage in clay vessels, became common in Neolithic communities?", "Pottery", "Papermaking", "Glassblowing", "Silk weaving"),
        ("What type of dwelling is typical of the Botai settlement in northern Kazakhstan?", "Semi-subterranean pit-houses", "Multi-storey mud-brick houses", "Stone-walled fortresses", "Floating reed houses"),
        ("What have residue studies of Botai pottery suggested about how horses were used?", "Mare's milk may have been consumed", "Horses were only used for sacrifices", "Horses were never eaten", "Horses were completely unknown there"),
        ("In which part of Kazakhstan are the ancient copper mines of the Zhezkazgan area located?", "Central Kazakhstan", "The Caspian coast", "The far south near Turkistan", "The Altai mountains"),
        ("Andronovo tribes are most often linked by scholars to which language family?", "Indo-Iranian", "Turkic", "Sino-Tibetan", "Semitic"),
        ("Which vehicle is closely associated with Andronovo-related cultures of the Bronze Age steppe?", "The spoke-wheeled chariot", "The steam locomotive", "The Roman galley", "The iron-shod sledge"),
        ("Which discipline, used alongside archaeology, studies the customs and way of life of peoples?", "Ethnography", "Cartography", "Geology", "Meteorology"),
        ("Which discipline studies coins as historical sources?", "Numismatics", "Epigraphy", "Heraldry", "Paleography"),
        ("According to the syllabus, what is the main aim of the History of Kazakhstan course?", "To give an objective understanding of the major stages of Kazakhstan's past", "To memorise dates without analysis", "To train students in military strategy", "To teach ancient languages only"),
        ("Which skills does the syllabus say the course should develop?", "Historical reasoning, critical analysis and research skills", "Only memorisation of dates", "Engineering design skills", "Musical composition skills"),
        ("How many ECTS credits is the course HK6002 History of Kazakhstan worth?", "5", "3", "4", "6"),
        ("Which Stone Age period lasted by far the longest?", "The Paleolithic", "The Neolithic", "The Mesolithic", "The Eneolithic"),
        ("Why are rock carvings (petroglyphs) valuable to historians?", "They show hunting scenes, animals and the ritual life of ancient people", "They contain written laws", "They record tax registers", "They list royal genealogies"),
        ("Radiocarbon dating helps archaeologists to do what?", "Estimate the age of organic remains such as bone and wood", "Translate ancient inscriptions", "Locate buried metal ores", "Measure the size of ancient armies"),
        ("The Botai culture belongs to roughly which time?", "About the 4th millennium BC", "About the 1st millennium BC", "About the 8th century AD", "About the 12th century AD"),
    ],
)

W[2] = dict(
    title="The Early Iron Age in Kazakhstan",
    essays=[
        "Analyze the political organization, economy and culture of the Saka tribes, and explain the significance of Saka animal-style art.",
        "Discuss the political history of the Hun Empire in Central Asia and its consequences for Eurasian history.",
        "Explain how the Usuns, Kangly and Sarmatians contributed to regional dynamics and to the ethnogenesis of the peoples of the steppe.",
    ],
    q=[
        ("In which year was the Issyk kurgan with the 'Golden Man' burial excavated?", "1969", "1937", "1956", "1991"),
        ("Who led the 1969 excavation that uncovered the Issyk 'Golden Man' burial?", "Kemal Akishev", "Alkey Margulan", "Lev Gumilev", "Nikolai Yadrintsev"),
        ("What was found written on the silver cup from the Issyk kurgan?", "A short line of text in a script whose reading is still debated", "A Persian royal decree", "A Greek poem", "A list of tribute payments"),
        ("Roughly how many gold items decorated the costume of the Issyk 'Golden Man'?", "About 4,000", "About 40", "About 400", "About 400,000"),
        ("The Berel kurgans, known for frozen burials with well-preserved horses, are located in which region?", "East Kazakhstan (Altai)", "Mangystau", "Kyzylorda", "Kostanay"),
        ("According to Herodotus, which queen of the Massagetae defeated Cyrus the Great?", "Tomyris", "Zarina", "Cleopatra", "Boadicea"),
        ("Around which year did Cyrus the Great die while campaigning against the Massagetae, according to tradition?", "About 530 BC", "About 330 BC", "About 130 BC", "About 30 BC"),
        ("Which short sword was typical of Saka warriors?", "The akinakes", "The katana", "The gladius", "The claymore"),
        ("In Persian royal inscriptions, the Saka who wore pointed hats were called what?", "Saka Tigrakhauda", "Saka Kipchak", "Saka Karluk", "Saka Oghuz"),
        ("Sarmatian tribes are mainly associated with which part of Kazakhstan?", "The west, toward the Ural (Zhaiyk) and Volga", "The far southeast", "The Altai", "The Balkhash shore"),
        ("Sarmatian graves often contain armed women, which historians link to Greek legends of which warriors?", "The Amazons", "The Titans", "The Spartans", "The Argonauts"),
        ("What do Chinese chronicles call the early nomadic empire often connected with the Huns?", "The Xiongnu", "The Xianbei", "The Sogdians", "The Tangut"),
        ("Which Hun leader led campaigns deep into Europe in the 5th century AD?", "Attila", "Bumin", "Genghis Khan", "Kasym Khan"),
        ("In which year did Attila's forces fight the Romans and Visigoths on the Catalaunian Plains?", "451 AD", "375 AD", "476 AD", "553 AD"),
        ("Which state built and extended long defensive walls partly to guard against nomadic raids such as those of the Xiongnu?", "China", "Byzantium", "Egypt", "India"),
        ("Which Han Chinese envoy travelled to the Usun and other Central Asian peoples in the 2nd century BC?", "Zhang Qian", "Marco Polo", "Herodotus", "Ibn Battuta"),
        ("Which title did the ruler of the Usuns bear in Chinese sources?", "Kunmo (Gunmi)", "Kagan", "Sultan", "Emir"),
        ("Which movable dwelling, made of felt over a wooden frame, became the classic home of steppe nomads?", "The yurt", "The igloo", "The pagoda", "The longhouse"),
        ("Which ancient Greek historian described steppe peoples such as the Massagetae?", "Herodotus", "Thucydides", "Plutarch", "Xenophon"),
        ("What were three-bladed bronze arrowheads, common in Saka graves, mainly designed for?", "Mounted archery in war and hunting", "Ploughing fields", "Weaving cloth", "Measuring land"),
    ],
)

W[3] = dict(
    title="Kazakhstan in the Turkic Era",
    essays=[
        "Explain the origins, rise and consolidation of power of the Great Turkic Khaganate and assess its historical significance.",
        "Analyze the role of the Great Silk Road in the economy, urbanization and cultural exchange of Kazakhstan in the Turkic era.",
        "Discuss the Muslim Renaissance in Central Asia and the contribution of outstanding Turkic scholars such as al-Farabi, Yusuf Balasaguni and Mahmud al-Kashgari.",
    ],
    q=[
        ("Which nomadic power did Bumin Khan overthrow in 552 to found the Turkic Khaganate?", "The Rouran", "The Xiongnu", "The Tang Dynasty", "The Sassanids"),
        ("Which relative of Bumin ruled the western Turkic lands and dealt with Persia and Byzantium?", "Istemi Yabgu", "Bilge Khan", "Kul-Tegin", "Tonyukuk"),
        ("The Orkhon inscriptions are written in which script?", "The Old Turkic (runiform) script", "Arabic script", "Cyrillic script", "Latin script"),
        ("Which Danish scholar deciphered the Old Turkic script in 1893?", "Vilhelm Thomsen", "Max Muller", "Nikolai Yadrintsev", "Wilhelm Radloff"),
        ("The Ten Arrows (On-Ok) of the Western Turkic Khaganate were divided into which two groups?", "Dulu and Nushibi", "Turgesh and Karluk", "Oghuz and Kipchak", "Kerey and Naiman"),
        ("Which belief system, centred on a sky god, was widespread among the early Turks?", "Tengrism", "Buddhism", "Zoroastrianism", "Christianity"),
        ("Which Iranian-speaking merchants dominated Silk Road trade across Central Asia?", "The Sogdians", "The Vikings", "The Phoenicians", "The Tibetans"),
        ("Which Turgesh ruler is known for resisting Arab advances into Transoxiana in the early 8th century?", "Suluk", "Bumin", "Kapagan", "Bilge"),
        ("Which Tang commander led the Chinese army at the Battle of Talas?", "Gao Xianzhi", "Zhang Qian", "Li Shimin", "Wu Zetian"),
        ("Which Turkic tribe's defection helped decide the Battle of Talas in favour of the Abbasids?", "The Karluks", "The Kipchaks", "The Oghuz", "The Naimans"),
        ("Which Karakhanid ruler is traditionally credited as the first Turkic ruler to accept Islam in the 10th century?", "Satuk Bughra Khan", "Bumin Khan", "Tamerlane", "Kasym Khan"),
        ("Which city in the Chu valley was an early Karakhanid capital and the birthplace of Yusuf Balasaguni?", "Balasagun", "Otrar", "Sygnak", "Sauran"),
        ("Around which years was Yusuf Balasaguni's Kutadgu Bilig completed?", "About 1069-1070", "About 751", "About 1206", "About 1465"),
        ("What is the title of Mahmud al-Kashgari's dictionary of the Turkic languages?", "Diwan Lughat at-Turk", "Kutadgu Bilig", "The Canon of Medicine", "Zhety Zhargy"),
        ("Which title is given to al-Farabi in the Islamic world?", "The Second Teacher, after Aristotle", "The First Teacher", "The Prince of Physicians", "The Sage of Samarkand"),
        ("Which 12th-century Sufi poet from Yasi (Turkistan) wrote the Diwan-i Hikmet?", "Khoja Ahmed Yasawi", "Al-Farabi", "Mahmud al-Kashgari", "Yusuf Balasaguni"),
        ("Which Turkic union ruled the Syr Darya region in the 9th-11th centuries with Yangikent as a centre?", "The Oghuz Yabgu State", "The Golden Horde", "The Nogai Horde", "The Kazakh Khanate"),
        ("Which Turkic khaganate of the 9th-11th centuries was centred on the Irtysh region?", "The Kimak Khaganate", "The Karakhanid state", "The Turgesh Khaganate", "The Western Turkic Khaganate"),
        ("Which ruler ordered the building of the great mausoleum of Khoja Ahmed Yasawi in Turkistan?", "Timur (Amir Temur)", "Genghis Khan", "Kasym Khan", "Bumin Khan"),
        ("Farab, the birthplace of al-Farabi, is identified with which Silk Road city on the Syr Darya?", "Otrar", "Taraz", "Sayram", "Bukhara"),
    ],
)
