# Weeks 10-12 (HK6002 syllabus). Format: (question, correct, wrong1, wrong2, wrong3)

W[10] = dict(
    title="Industrialization and Collectivization",
    essays=[
        "What were the main features of collectivization in Kazakhstan and what were its consequences?",
        "Analyze Soviet industrialization in Kazakhstan: the five-year plans, sectoral priorities, infrastructure, new industrial centers and urbanization.",
        "Explain the political persecutions of the 1930s, the Great Terror and the prison-camp system, and their social and cultural impact on Kazakhstan.",
    ],
    q=[
        ("Which years did the First Five-Year Plan of the USSR cover?", "1928-1932", "1921-1925", "1941-1945", "1953-1958"),
        ("The Turksib railway connected Turkestan with which region?", "Siberia", "The Caucasus", "The Volga region", "Manchuria"),
        ("Which Kazakh region became a major coal-mining centre in the 1930s?", "Karaganda", "Mangystau", "Kyzylorda", "Zhetysu"),
        ("Which mineral resource was the focus of the Balkhash and Zhezkazgan industrial development?", "Copper", "Uranium", "Oil", "Gold"),
        ("By roughly how much did livestock numbers in Kazakhstan fall during collectivization?", "By about nine-tenths", "By about 5 per cent", "By about a quarter", "They rose sharply"),
        ("By widely cited estimates, roughly how many lives did the famine of 1931-1933 cost Kazakhstan?", "About 1.5 million", "About 15,000", "About 150,000", "About 15 million"),
        ("By 1939, Kazakhs made up about what share of the republic's population?", "About 38 per cent", "About 80 per cent", "About 65 per cent", "About 95 per cent"),
        ("What was a kolkhoz?", "A collective farm whose members pooled land and livestock", "A private khan's estate", "A Cossack military settlement", "A state-run factory"),
        ("What was a sovkhoz?", "A state-owned farm with hired workers", "A voluntary cooperative of nomads", "A private estate", "A trading company"),
        ("In Soviet policy, what did the term 'kulak' mean?", "A wealthier peasant labelled a class enemy", "A factory worker", "A Red Army officer", "A village teacher"),
        ("What did forced sedentarization mean for Kazakh herders?", "They were compelled to settle in fixed villages and farms", "They were given new pastures to roam", "They were moved to cities as officials", "They were exempted from all duties"),
        ("Why did collectivization devastate the traditional pastoral economy?", "Herds were confiscated and pooled, and many animals died or were slaughtered", "Pastures were sold abroad", "Herders were given tractors", "Nomads were rewarded with land"),
        ("Which large prison-camp complex was located near Karaganda?", "Karlag", "Kolyma", "Vorkuta", "Solovki"),
        ("For whom was the ALZHIR camp near Akmolinsk created?", "Wives of men labelled 'traitors of the Motherland'", "Prisoners of war only", "Foreign diplomats", "Deported Cossacks"),
        ("Which people were deported from the Soviet Far East to Kazakhstan and Central Asia in 1937?", "Koreans", "Buryats", "Yakuts", "Karelians"),
        ("Which years mark the height of the Great Terror?", "1937-1938", "1921-1922", "1931-1933", "1941-1945"),
        ("In which year did the Kazakh language switch from the Latin to the Cyrillic alphabet?", "1940", "1929", "1936", "1991"),
        ("Which university, now named after a great philosopher, was founded in Almaty in 1934?", "Al-Farabi Kazakh National University", "Nazarbayev University", "The Eurasian National University", "IITU"),
        ("Who was persecuted as 'nationalists' in the 1930s?", "Members of the Kazakh national intelligentsia, including former Alash figures", "Only foreign engineers", "Only Red Army generals", "Only factory managers"),
        ("What was one demographic effect of industrialization in Kazakhstan?", "Rapid urbanization and labour migration into new industrial towns", "The end of all migration", "A return to nomadism", "A fall in the number of cities"),
    ],
)

W[11] = dict(
    title="Kazakhstan in the Great Patriotic War and Postwar Years",
    essays=[
        "Analyze Kazakhstan's contribution to victory in the Great Patriotic War (1941-1945): human resources, industry, agriculture and the home front.",
        "Describe Kazakhstan's postwar development (1946-1953), including reconstruction, the famine of 1946-1947, repression and the Bekmakhanov case.",
        "Assess the Virgin Lands campaign and the impact of nuclear testing and environmental damage on Kazakhstan during Khrushchev's decade.",
    ],
    q=[
        ("About how many people from Kazakhstan fought at the front in the Great Patriotic War?", "About 1.2 million", "About 120,000", "About 12 million", "About 12,000"),
        ("Which division, formed in Alma-Ata, fought in the defence of Moscow in 1941?", "The 316th Rifle Division (Panfilov's)", "The Alash Division", "The Turgai Corps", "The Golden Horde Regiment"),
        ("Which Kazakh officer, celebrated in Alexander Bek's 'Volokolamsk Highway', fought under Panfilov?", "Bauyrzhan Momyshuly", "Amangeldy Imanov", "Sabit Mukanov", "Mukhtar Auezov"),
        ("Which Kazakh machine-gunner, killed at Nevel in 1943, became a Hero of the Soviet Union?", "Manshuk Mametova", "Aliya Moldagulova", "Kulash Baiseitova", "Tamara Kazakova"),
        ("Roughly how many industrial enterprises were evacuated to Kazakhstan during the war?", "More than 200", "About 5", "About 20", "None"),
        ("Which peoples were deported to Kazakhstan in 1944?", "Chechens and Ingush", "Kazakhs of Xinjiang", "Yakuts", "Tuvans"),
        ("Which historian was condemned in 1951 for his book on Kazakhstan in the 1820s-1840s?", "Yerkegali Bekmakhanov", "Alkey Margulan", "Kanysh Satpayev", "Chokan Valikhanov"),
        ("Who was the first president of the Kazakh SSR Academy of Sciences founded in 1946?", "Kanysh Satpayev", "Alkey Margulan", "Mukhtar Auezov", "Yerkegali Bekmakhanov"),
        ("In which year did the Virgin Lands campaign begin?", "1954", "1941", "1965", "1930"),
        ("By about 1960, roughly how much steppe had been ploughed in Kazakhstan under the Virgin Lands campaign?", "More than 25 million hectares", "About 2 million hectares", "About 250,000 hectares", "About 2.5 billion hectares"),
        ("Which name did the city now called Astana bear from 1961, reflecting the Virgin Lands campaign?", "Tselinograd", "Akmolinsk", "Nur-Sultan", "Karaganda"),
        ("What was a long-term ecological problem of the Virgin Lands campaign?", "Soil erosion and dust storms", "Flooding of the steppe", "The spread of forests", "The melting of glaciers"),
        ("In which year was the first Soviet nuclear bomb tested at the Semipalatinsk site?", "1949", "1941", "1953", "1991"),
        ("In which year was the Semipalatinsk nuclear test site closed?", "1991", "1949", "1963", "1986"),
        ("What mainly caused the shrinking of the Aral Sea?", "The diversion of the Amu Darya and Syr Darya for irrigation", "A meteor impact", "The closing of the Caspian Sea", "Nuclear tests"),
        ("From which cosmodrome in Kazakhstan did Yuri Gagarin launch in 1961?", "Baikonur", "Plesetsk", "Cape Canaveral", "Semey"),
        ("What were the effects of nuclear testing on the people of eastern Kazakhstan?", "Long-term health problems and environmental damage", "A population boom", "Better harvests", "No measurable effects"),
        ("What role did Kazakhstan's agriculture play during the war?", "It supplied grain, meat and other food to the front and the cities", "It fed only its own population", "It stopped production", "It exported food to Germany"),
        ("Which Kazakh industries expanded to serve the war effort?", "Metallurgy, mining and munitions", "Luxury goods", "Tourism", "Film-making only"),
        ("Which years does the syllabus call 'Khrushchev's decade'?", "1953-1964", "1941-1945", "1965-1985", "1985-1991"),
    ],
)

W[12] = dict(
    title="Kazakhstan from 1965 to 1991",
    essays=[
        "What were the causes and historical significance of the December 1986 events in Almaty?",
        "Describe the Brezhnev era of 'stagnation' in Kazakhstan: industrial growth, agricultural challenges, urbanization and Russification.",
        "Explain the path from perestroika and glasnost to the Declaration of Sovereignty (October 25, 1990) and the Independence Law (December 16, 1991).",
    ],
    q=[
        ("Who led the Communist Party of Kazakhstan from 1964 to 1986?", "Dinmukhamed Kunayev", "Gennady Kolbin", "Nursultan Nazarbayev", "Leonid Brezhnev"),
        ("Who replaced Dinmukhamed Kunayev as Kazakh party leader in December 1986?", "Gennady Kolbin", "Nursultan Nazarbayev", "Mikhail Gorbachev", "Olzhas Suleimenov"),
        ("What sparked the December 1986 protests in Alma-Ata?", "Moscow's replacement of Kunayev with an outsider, Kolbin", "A famine", "A new tax", "A nuclear accident"),
        ("In which square in Alma-Ata did the December 1986 protest gather?", "Brezhnev Square (now Republic Square)", "Red Square", "Tiananmen Square", "Palace Square"),
        ("How did the Soviet authorities respond to the December 1986 protests?", "They dispersed the crowds by force and prosecuted participants", "They accepted every demand", "They ignored the protests", "They moved the capital"),
        ("Who became First Secretary of the Communist Party of Kazakhstan in 1989?", "Nursultan Nazarbayev", "Gennady Kolbin", "Dinmukhamed Kunayev", "Olzhas Suleimenov"),
        ("Which poet founded the anti-nuclear Nevada-Semipalatinsk movement in 1989?", "Olzhas Suleimenov", "Mukhtar Shakhanov", "Abai Kunanbayev", "Mukhtar Auezov"),
        ("Which 1975 book by Olzhas Suleimenov, on the Turkic world and the Tale of Igor's Campaign, caused controversy?", "Az i Ya", "Abai Zholy", "Kutadgu Bilig", "The Book of Words"),
        ("What was the aim of Gorbachev's perestroika?", "To restructure the Soviet economy and political system", "To restore the tsarist regime", "To expand the Virgin Lands", "To abolish all trade"),
        ("What did glasnost mean?", "Openness and freer public discussion", "Restructuring of the economy", "A return to Stalinist rule", "A new military doctrine"),
        ("Which policy of the Gorbachev era allowed national movements to grow?", "Political liberalization under glasnost", "Tighter censorship", "Collectivization", "Military Communism"),
        ("Why is the Brezhnev era called the era of 'stagnation'?", "Economic growth slowed and reforms stalled", "The population fell sharply", "Trade with the West boomed", "The USSR expanded its borders"),
        ("In the 1959 census, which group formed the largest share of Kazakhstan's population?", "Russians", "Kazakhs", "Ukrainians", "Germans"),
        ("Which epic novel by Mukhtar Auezov portrays the life of Abai?", "Abai Zholy (The Path of Abai)", "Koblandy Batyr", "Enlik-Kebek", "Kutadgu Bilig"),
        ("Which law of 1989 made Kazakh the state language of the Kazakh SSR?", "The Law on Languages", "The Law on Land", "The Law on Sovereignty", "The Law on the Press"),
        ("On what date was the Declaration of State Sovereignty of the Kazakh SSR adopted?", "October 25, 1990", "December 16, 1991", "August 29, 1991", "March 17, 1991"),
        ("In the March 1991 all-Union referendum, most voters in Kazakhstan supported what?", "Preserving the USSR as a renewed federation", "Immediate independence", "Joining China", "Restoring the khanate"),
        ("Who was elected the first President of Kazakhstan in December 1991?", "Nursultan Nazarbayev", "Dinmukhamed Kunayev", "Gennady Kolbin", "Olzhas Suleimenov"),
        ("Who was the first Kazakh cosmonaut, flying in 1991?", "Tokhtar Aubakirov", "Yuri Gagarin", "Alexei Leonov", "Valentina Tereshkova"),
        ("Which trend marked Kazakhstan's population between 1965 and 1985?", "Rapid urban growth and large in-migration", "A fall in city populations", "A return to nomadic life", "A ban on migration"),
    ],
)
